### ISSUE TITLE
Request for hardware environment details

### ISSUE THREAD

**Issue by ZhouHao524** [cvlab-yonsei/Multi-Task-Learning#6]
Hello,
Could you please share the hardware settings you used for this project? Specifically, I’d like to know details about your GPU, driver version, and CUDA version.
Thank you in advance!

**Comment by hw-ch0** [comment]
Hello, thank you for your interest in our project! Here are the hardware settings we used:
GPU: NVIDIA GeForce RTX 2080 Ti
Driver Version: NVIDIA_SMI 525.116
CUDA Version: 12.0
VRAM Usage: Slightly over 7000MB

Please let us know if you need any additional details.
